# è¯·å¯¹ä¸€ä¸‹github action flow é…ç½®åšä¸€äº›è§£é‡Š
on:
  push: # å½“ç”¨æˆ·pushä»£ç åˆ°ä»£ç ä»“åº“mainåˆ†æ”¯æ—¶è§¦å‘github action
    branches:
      - main
  schedule: # å®šæ—¶è§¦å‘github action
    - cron: "0 0 */1 * *" # è¿™é‡Œè®¾ç½®çš„æ¯å¤©è§¦å‘ä¸€æ¬¡ï¼Œå…·ä½“é…ç½®å¯ä»¥è‡ªè¡Œäº†è§£Cronè¡¨è¾¾å¼çŸ¥è¯†
  workflow_dispatch: # GitHub Actions ä¸­çš„ä¸€ç§è§¦å‘å™¨ï¼Œç”¨äºæ‰‹åŠ¨è§¦å‘å·¥ä½œæµï¼ˆWorkflowï¼‰ã€‚å®ƒå…è®¸ç”¨æˆ·é€šè¿‡ GitHub ç•Œé¢æˆ– API æ‰‹åŠ¨å¯åŠ¨ä¸€ä¸ªå·¥ä½œæµï¼Œè€Œä¸æ˜¯ä¾èµ–äºäº‹ä»¶
permissions:
  contents: write # ä¸€ç§æœ€ç®€å•çš„æˆäºˆgithub action å†™æƒé™çš„æ–¹å¼

name: Build and Deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # æŒ‡å®šè¿è¡Œä»»åŠ¡çš„ç¯å¢ƒï¼Œè¿™é‡Œæ˜¯ ubuntu-latestã€‚
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4 #æ£€å‡ºä»£ç ä»“åº“ã€‚
      - name: run your customized script # è‡ªå®šä¹‰è„šæœ¬
        run: gh-pages_script.sh
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4 #ä½¿ç”¨ç¬¬ä¸‰æ–¹ Action å°†æ„å»ºåçš„æ–‡ä»¶éƒ¨ç½²åˆ° GitHub Pagesã€‚
        with:
          folder: "dest"
